version: 2

models:
  - name: stg_customers
    description: Customer Model
    columns:
      - name: customer_id
        description: Primary key
        tests:
          - unique
          - not_null

  - name: stg_orders
    description: Incremental Orders Table
    columns:
      - name: order_id
        description: Primary key
        tests:
          - unique
          - not_null