{{ config(
    materialized = 'view'
) }}

WITH DISC_CATEGORIES AS (

    SELECT
        DISTINCT CATEGORY
    FROM
        {{ ref('ORDERS_PRODUCTS') }}
)
SELECT
    DC.CATEGORY,
    COALESCE(COUNT(OP.ORDER_ID), 0) AS TOTAL_ORDERS
FROM
    DISC_CATEGORIES DC
    LEFT JOIN {{ ref('ORDERS_PRODUCTS') }}
    OP
    ON DC.CATEGORY = OP.CATEGORY
GROUP BY
    DC.CATEGORY
